In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [37]:
"""
the difference between xy and xy1:
pd.read_csv reads from second row, because it recognizes first row as column_name
on the other hand, np.loadtxt reads from first row
"""
xy = np.loadtxt('./data/data-01-test-score.csv', delimiter=',', dtype=np.float32)
xy1 = np.array(pd.read_csv("./data/data-01-test-score.csv"), dtype='float32')

In [44]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [55]:
# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print('-'*30)
print(y_data, "\ny_data shape:", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
------------------------------
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [56]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(units=1, input_dim=3))
model.add(tf.keras.layers.Activation('linear'))

In [59]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 4         
_________________________________________________________________
activation (Activation)      (None, 1)                 0         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [61]:
model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
history = model.fit(x_data, y_data, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 1s 514ms/step - loss: 22993.9395
Epoch 2/2000
1/1 [==============================] - 0s 2ms/step - loss: 8519.7305
Epoch 3/2000
1/1 [==============================] - 0s 3ms/step - loss: 3168.2061
Epoch 4/2000
1/1 [==============================] - 0s 2ms/step - loss: 1189.5902
Epoch 5/2000
1/1 [==============================] - 0s 2ms/step - loss: 458.0332
Epoch 6/2000
1/1 [==============================] - 0s 2ms/step - loss: 187.5482
Epoch 7/2000
1/1 [==============================] - 0s 3ms/step - loss: 87.5340
Epoch 8/2000
1/1 [==============================] - 0s 2ms/step - loss: 50.5475
Epoch 9/2000
1/1 [==============================] - 0s 3ms/step - loss: 36.8642
Epoch 10/2000
1/1 [==============================] - 0s 2ms/step - loss: 31.7968
Epoch 11/2000
1/1 [==============================] - 0s 2ms/step - loss: 29.9148
Epoch 12/2000
1/1 [==============================] - 0s 2ms/step - loss: 29.2105
Epoch 13/2000
1/1 [=====

1/1 [==============================] - 0s 3ms/step - loss: 27.6527
Epoch 102/2000
1/1 [==============================] - 0s 2ms/step - loss: 27.6401
Epoch 103/2000
1/1 [==============================] - 0s 2ms/step - loss: 27.6275
Epoch 104/2000
1/1 [==============================] - 0s 2ms/step - loss: 27.6150
Epoch 105/2000
1/1 [==============================] - 0s 3ms/step - loss: 27.6024
Epoch 106/2000
1/1 [==============================] - 0s 1ms/step - loss: 27.5899
Epoch 107/2000
1/1 [==============================] - 0s 2ms/step - loss: 27.5773
Epoch 108/2000
1/1 [==============================] - 0s 2ms/step - loss: 27.5648
Epoch 109/2000
1/1 [==============================] - 0s 2ms/step - loss: 27.5522
Epoch 110/2000
1/1 [==============================] - 0s 3ms/step - loss: 27.5397
Epoch 111/2000
1/1 [==============================] - 0s 2ms/step - loss: 27.5272
Epoch 112/2000
1/1 [==============================] - 0s 3ms/step - loss: 27.5147
Epoch 113/2000
1/1 [===========

1/1 [==============================] - 0s 2ms/step - loss: 26.4323
Epoch 202/2000
1/1 [==============================] - 0s 3ms/step - loss: 26.4205
Epoch 203/2000
1/1 [==============================] - 0s 2ms/step - loss: 26.4087
Epoch 204/2000
1/1 [==============================] - 0s 3ms/step - loss: 26.3969
Epoch 205/2000
1/1 [==============================] - 0s 2ms/step - loss: 26.3851
Epoch 206/2000
1/1 [==============================] - 0s 3ms/step - loss: 26.3733
Epoch 207/2000
1/1 [==============================] - 0s 2ms/step - loss: 26.3615
Epoch 208/2000
1/1 [==============================] - 0s 2ms/step - loss: 26.3497
Epoch 209/2000
1/1 [==============================] - 0s 2ms/step - loss: 26.3380
Epoch 210/2000
1/1 [==============================] - 0s 3ms/step - loss: 26.3262
Epoch 211/2000
1/1 [==============================] - 0s 2ms/step - loss: 26.3144
Epoch 212/2000
1/1 [==============================] - 0s 2ms/step - loss: 26.3027
Epoch 213/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 25.2859
Epoch 302/2000
1/1 [==============================] - 0s 3ms/step - loss: 25.2747
Epoch 303/2000
1/1 [==============================] - 0s 2ms/step - loss: 25.2636
Epoch 304/2000
1/1 [==============================] - 0s 4ms/step - loss: 25.2525
Epoch 305/2000
1/1 [==============================] - 0s 2ms/step - loss: 25.2415
Epoch 306/2000
1/1 [==============================] - 0s 2ms/step - loss: 25.2304
Epoch 307/2000
1/1 [==============================] - 0s 2ms/step - loss: 25.2193
Epoch 308/2000
1/1 [==============================] - 0s 3ms/step - loss: 25.2083
Epoch 309/2000
1/1 [==============================] - 0s 2ms/step - loss: 25.1972
Epoch 310/2000
1/1 [==============================] - 0s 3ms/step - loss: 25.1861
Epoch 311/2000
1/1 [==============================] - 0s 3ms/step - loss: 25.1751
Epoch 312/2000
1/1 [==============================] - 0s 2ms/step - loss: 25.1640
Epoch 313/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 24.2085
Epoch 402/2000
1/1 [==============================] - 0s 2ms/step - loss: 24.1981
Epoch 403/2000
1/1 [==============================] - 0s 1ms/step - loss: 24.1876
Epoch 404/2000
1/1 [==============================] - 0s 2ms/step - loss: 24.1772
Epoch 405/2000
1/1 [==============================] - 0s 3ms/step - loss: 24.1668
Epoch 406/2000
1/1 [==============================] - 0s 2ms/step - loss: 24.1564
Epoch 407/2000
1/1 [==============================] - 0s 2ms/step - loss: 24.1460
Epoch 408/2000
1/1 [==============================] - 0s 2ms/step - loss: 24.1356
Epoch 409/2000
1/1 [==============================] - 0s 4ms/step - loss: 24.1252
Epoch 410/2000
1/1 [==============================] - 0s 2ms/step - loss: 24.1148
Epoch 411/2000
1/1 [==============================] - 0s 2ms/step - loss: 24.1044
Epoch 412/2000
1/1 [==============================] - 0s 1ms/step - loss: 24.0940
Epoch 413/2000
1/1 [===========

1/1 [==============================] - 0s 2ms/step - loss: 23.1958
Epoch 502/2000
1/1 [==============================] - 0s 3ms/step - loss: 23.1860
Epoch 503/2000
1/1 [==============================] - 0s 2ms/step - loss: 23.1761
Epoch 504/2000
1/1 [==============================] - 0s 2ms/step - loss: 23.1664
Epoch 505/2000
1/1 [==============================] - 0s 3ms/step - loss: 23.1565
Epoch 506/2000
1/1 [==============================] - 0s 2ms/step - loss: 23.1468
Epoch 507/2000
1/1 [==============================] - 0s 2ms/step - loss: 23.1370
Epoch 508/2000
1/1 [==============================] - 0s 3ms/step - loss: 23.1272
Epoch 509/2000
1/1 [==============================] - 0s 2ms/step - loss: 23.1174
Epoch 510/2000
1/1 [==============================] - 0s 2ms/step - loss: 23.1077
Epoch 511/2000
1/1 [==============================] - 0s 2ms/step - loss: 23.0979
Epoch 512/2000
1/1 [==============================] - 0s 3ms/step - loss: 23.0881
Epoch 513/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 22.2435
Epoch 602/2000
1/1 [==============================] - 0s 2ms/step - loss: 22.2342
Epoch 603/2000
1/1 [==============================] - 0s 3ms/step - loss: 22.2250
Epoch 604/2000
1/1 [==============================] - 0s 2ms/step - loss: 22.2158
Epoch 605/2000
1/1 [==============================] - 0s 2ms/step - loss: 22.2066
Epoch 606/2000
1/1 [==============================] - 0s 4ms/step - loss: 22.1974
Epoch 607/2000
1/1 [==============================] - 0s 2ms/step - loss: 22.1882
Epoch 608/2000
1/1 [==============================] - 0s 3ms/step - loss: 22.1790
Epoch 609/2000
1/1 [==============================] - 0s 3ms/step - loss: 22.1698
Epoch 610/2000
1/1 [==============================] - 0s 2ms/step - loss: 22.1606
Epoch 611/2000
1/1 [==============================] - 0s 3ms/step - loss: 22.1514
Epoch 612/2000
1/1 [==============================] - 0s 2ms/step - loss: 22.1422
Epoch 613/2000
1/1 [===========

1/1 [==============================] - 0s 2ms/step - loss: 21.3477
Epoch 702/2000
1/1 [==============================] - 0s 2ms/step - loss: 21.3390
Epoch 703/2000
1/1 [==============================] - 0s 2ms/step - loss: 21.3304
Epoch 704/2000
1/1 [==============================] - 0s 2ms/step - loss: 21.3217
Epoch 705/2000
1/1 [==============================] - 0s 2ms/step - loss: 21.3130
Epoch 706/2000
1/1 [==============================] - 0s 2ms/step - loss: 21.3044
Epoch 707/2000
1/1 [==============================] - 0s 2ms/step - loss: 21.2957
Epoch 708/2000
1/1 [==============================] - 0s 3ms/step - loss: 21.2870
Epoch 709/2000
1/1 [==============================] - 0s 3ms/step - loss: 21.2784
Epoch 710/2000
1/1 [==============================] - 0s 2ms/step - loss: 21.2697
Epoch 711/2000
1/1 [==============================] - 0s 2ms/step - loss: 21.2611
Epoch 712/2000
1/1 [==============================] - 0s 4ms/step - loss: 21.2525
Epoch 713/2000
1/1 [===========

1/1 [==============================] - 0s 2ms/step - loss: 20.5049
Epoch 802/2000
1/1 [==============================] - 0s 2ms/step - loss: 20.4967
Epoch 803/2000
1/1 [==============================] - 0s 3ms/step - loss: 20.4885
Epoch 804/2000
1/1 [==============================] - 0s 2ms/step - loss: 20.4804
Epoch 805/2000
1/1 [==============================] - 0s 2ms/step - loss: 20.4722
Epoch 806/2000
1/1 [==============================] - 0s 2ms/step - loss: 20.4641
Epoch 807/2000
1/1 [==============================] - 0s 3ms/step - loss: 20.4559
Epoch 808/2000
1/1 [==============================] - 0s 3ms/step - loss: 20.4478
Epoch 809/2000
1/1 [==============================] - 0s 995us/step - loss: 20.4397
Epoch 810/2000
1/1 [==============================] - 0s 2ms/step - loss: 20.4315
Epoch 811/2000
1/1 [==============================] - 0s 2ms/step - loss: 20.4234
Epoch 812/2000
1/1 [==============================] - 0s 2ms/step - loss: 20.4153
Epoch 813/2000
1/1 [=========

1/1 [==============================] - 0s 2ms/step - loss: 19.7116
Epoch 902/2000
1/1 [==============================] - 0s 3ms/step - loss: 19.7039
Epoch 903/2000
1/1 [==============================] - 0s 2ms/step - loss: 19.6963
Epoch 904/2000
1/1 [==============================] - 0s 2ms/step - loss: 19.6886
Epoch 905/2000
1/1 [==============================] - 0s 3ms/step - loss: 19.6809
Epoch 906/2000
1/1 [==============================] - 0s 2ms/step - loss: 19.6732
Epoch 907/2000
1/1 [==============================] - 0s 3ms/step - loss: 19.6655
Epoch 908/2000
1/1 [==============================] - 0s 2ms/step - loss: 19.6579
Epoch 909/2000
1/1 [==============================] - 0s 3ms/step - loss: 19.6502
Epoch 910/2000
1/1 [==============================] - 0s 4ms/step - loss: 19.6425
Epoch 911/2000
1/1 [==============================] - 0s 2ms/step - loss: 19.6349
Epoch 912/2000
1/1 [==============================] - 0s 3ms/step - loss: 19.6273
Epoch 913/2000
1/1 [===========

1/1 [==============================] - 0s 2ms/step - loss: 18.9648
Epoch 1002/2000
1/1 [==============================] - 0s 2ms/step - loss: 18.9575
Epoch 1003/2000
1/1 [==============================] - 0s 2ms/step - loss: 18.9503
Epoch 1004/2000
1/1 [==============================] - 0s 2ms/step - loss: 18.9431
Epoch 1005/2000
1/1 [==============================] - 0s 3ms/step - loss: 18.9358
Epoch 1006/2000
1/1 [==============================] - 0s 1ms/step - loss: 18.9286
Epoch 1007/2000
1/1 [==============================] - ETA: 0s - loss: 18.92 - 0s 3ms/step - loss: 18.9214
Epoch 1008/2000
1/1 [==============================] - 0s 3ms/step - loss: 18.9142
Epoch 1009/2000
1/1 [==============================] - 0s 3ms/step - loss: 18.9070
Epoch 1010/2000
1/1 [==============================] - 0s 2ms/step - loss: 18.8997
Epoch 1011/2000
1/1 [==============================] - 0s 2ms/step - loss: 18.8925
Epoch 1012/2000
1/1 [==============================] - 0s 3ms/step - loss: 18.8

1/1 [==============================] - 0s 2ms/step - loss: 18.2751
Epoch 1100/2000
1/1 [==============================] - 0s 3ms/step - loss: 18.2683
Epoch 1101/2000
1/1 [==============================] - 0s 2ms/step - loss: 18.2614
Epoch 1102/2000
1/1 [==============================] - 0s 3ms/step - loss: 18.2546
Epoch 1103/2000
1/1 [==============================] - 0s 2ms/step - loss: 18.2478
Epoch 1104/2000
1/1 [==============================] - 0s 2ms/step - loss: 18.2410
Epoch 1105/2000
1/1 [==============================] - 0s 2ms/step - loss: 18.2342
Epoch 1106/2000
1/1 [==============================] - 0s 2ms/step - loss: 18.2274
Epoch 1107/2000
1/1 [==============================] - 0s 3ms/step - loss: 18.2205
Epoch 1108/2000
1/1 [==============================] - 0s 2ms/step - loss: 18.2138
Epoch 1109/2000
1/1 [==============================] - 0s 2ms/step - loss: 18.2070
Epoch 1110/2000
1/1 [==============================] - 0s 3ms/step - loss: 18.2002
Epoch 1111/2000
1/1 

1/1 [==============================] - 0s 2ms/step - loss: 17.6246
Epoch 1198/2000
1/1 [==============================] - 0s 2ms/step - loss: 17.6182
Epoch 1199/2000
1/1 [==============================] - 0s 2ms/step - loss: 17.6117
Epoch 1200/2000
1/1 [==============================] - 0s 3ms/step - loss: 17.6053
Epoch 1201/2000
1/1 [==============================] - 0s 3ms/step - loss: 17.5989
Epoch 1202/2000
1/1 [==============================] - 0s 2ms/step - loss: 17.5924
Epoch 1203/2000
1/1 [==============================] - 0s 3ms/step - loss: 17.5860
Epoch 1204/2000
1/1 [==============================] - 0s 3ms/step - loss: 17.5796
Epoch 1205/2000
1/1 [==============================] - 0s 4ms/step - loss: 17.5732
Epoch 1206/2000
1/1 [==============================] - 0s 3ms/step - loss: 17.5668
Epoch 1207/2000
1/1 [==============================] - 0s 2ms/step - loss: 17.5603
Epoch 1208/2000
1/1 [==============================] - 0s 2ms/step - loss: 17.5539
Epoch 1209/2000
1/1 

1/1 [==============================] - 0s 3ms/step - loss: 17.0110
Epoch 1296/2000
1/1 [==============================] - 0s 3ms/step - loss: 17.0049
Epoch 1297/2000
1/1 [==============================] - 0s 3ms/step - loss: 16.9988
Epoch 1298/2000
1/1 [==============================] - 0s 1ms/step - loss: 16.9927
Epoch 1299/2000
1/1 [==============================] - 0s 2ms/step - loss: 16.9867
Epoch 1300/2000
1/1 [==============================] - 0s 2ms/step - loss: 16.9806
Epoch 1301/2000
1/1 [==============================] - 0s 3ms/step - loss: 16.9745
Epoch 1302/2000
1/1 [==============================] - 0s 2ms/step - loss: 16.9685
Epoch 1303/2000
1/1 [==============================] - 0s 3ms/step - loss: 16.9624
Epoch 1304/2000
1/1 [==============================] - 0s 3ms/step - loss: 16.9564
Epoch 1305/2000
1/1 [==============================] - 0s 1ms/step - loss: 16.9503
Epoch 1306/2000
1/1 [==============================] - 0s 4ms/step - loss: 16.9443
Epoch 1307/2000
1/1 

1/1 [==============================] - 0s 4ms/step - loss: 16.4319
Epoch 1394/2000
1/1 [==============================] - 0s 2ms/step - loss: 16.4261
Epoch 1395/2000
1/1 [==============================] - 0s 2ms/step - loss: 16.4204
Epoch 1396/2000
1/1 [==============================] - 0s 2ms/step - loss: 16.4147
Epoch 1397/2000
1/1 [==============================] - 0s 3ms/step - loss: 16.4089
Epoch 1398/2000
1/1 [==============================] - 0s 3ms/step - loss: 16.4032
Epoch 1399/2000
1/1 [==============================] - 0s 3ms/step - loss: 16.3975
Epoch 1400/2000
1/1 [==============================] - 0s 3ms/step - loss: 16.3918
Epoch 1401/2000
1/1 [==============================] - 0s 2ms/step - loss: 16.3860
Epoch 1402/2000
1/1 [==============================] - 0s 3ms/step - loss: 16.3803
Epoch 1403/2000
1/1 [==============================] - 0s 2ms/step - loss: 16.3746
Epoch 1404/2000
1/1 [==============================] - 0s 4ms/step - loss: 16.3689
Epoch 1405/2000
1/1 

1/1 [==============================] - 0s 3ms/step - loss: 15.8853
Epoch 1492/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.8799
Epoch 1493/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.8744
Epoch 1494/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.8690
Epoch 1495/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.8636
Epoch 1496/2000
1/1 [==============================] - 0s 3ms/step - loss: 15.8582
Epoch 1497/2000
1/1 [==============================] - 0s 3ms/step - loss: 15.8528
Epoch 1498/2000
1/1 [==============================] - 0s 3ms/step - loss: 15.8474
Epoch 1499/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.8420
Epoch 1500/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.8366
Epoch 1501/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.8312
Epoch 1502/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.8259
Epoch 1503/2000
1/1 

1/1 [==============================] - 0s 2ms/step - loss: 15.3692
Epoch 1590/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.3641
Epoch 1591/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.3590
Epoch 1592/2000
1/1 [==============================] - 0s 3ms/step - loss: 15.3539
Epoch 1593/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.3488
Epoch 1594/2000
1/1 [==============================] - 0s 3ms/step - loss: 15.3437
Epoch 1595/2000
1/1 [==============================] - 0s 3ms/step - loss: 15.3386
Epoch 1596/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.3335
Epoch 1597/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.3284
Epoch 1598/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.3233
Epoch 1599/2000
1/1 [==============================] - 0s 1ms/step - loss: 15.3182
Epoch 1600/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.3131
Epoch 1601/2000
1/1 

1/1 [==============================] - 0s 2ms/step - loss: 14.8819
Epoch 1688/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.8770
Epoch 1689/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.8722
Epoch 1690/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.8674
Epoch 1691/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.8625
Epoch 1692/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.8577
Epoch 1693/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.8529
Epoch 1694/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.8481
Epoch 1695/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.8433
Epoch 1696/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.8385
Epoch 1697/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.8337
Epoch 1698/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.8289
Epoch 1699/2000
1/1 

1/1 [==============================] - 0s 2ms/step - loss: 14.4215
Epoch 1786/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.4169
Epoch 1787/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.4124
Epoch 1788/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.4078
Epoch 1789/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.4033
Epoch 1790/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.3987
Epoch 1791/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.3941
Epoch 1792/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.3896
Epoch 1793/2000
1/1 [==============================] - ETA: 0s - loss: 14.38 - 0s 2ms/step - loss: 14.3850
Epoch 1794/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.3805
Epoch 1795/2000
1/1 [==============================] - 0s 3ms/step - loss: 14.3760
Epoch 1796/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.3

1/1 [==============================] - 0s 1ms/step - loss: 13.9865
Epoch 1884/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.9822
Epoch 1885/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.9779
Epoch 1886/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.9736
Epoch 1887/2000
1/1 [==============================] - 0s 1ms/step - loss: 13.9693
Epoch 1888/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.9650
Epoch 1889/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.9607
Epoch 1890/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.9564
Epoch 1891/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.9521
Epoch 1892/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.9478
Epoch 1893/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.9435
Epoch 1894/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.9392
Epoch 1895/2000
1/1 

1/1 [==============================] - 0s 3ms/step - loss: 13.5755
Epoch 1982/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.5714
Epoch 1983/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.5673
Epoch 1984/2000
1/1 [==============================] - 0s 1ms/step - loss: 13.5632
Epoch 1985/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.5592
Epoch 1986/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.5551
Epoch 1987/2000
1/1 [==============================] - 0s 4ms/step - loss: 13.5510
Epoch 1988/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.5470
Epoch 1989/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.5429
Epoch 1990/2000
1/1 [==============================] - 0s 1ms/step - loss: 13.5389
Epoch 1991/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.5348
Epoch 1992/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.5308
Epoch 1993/2000
1/1 

In [63]:
# Ask my score
print("Your score will be ", model.predict([[100, 70, 101]]))
print("Other scores will be ", model.predict([[60, 70, 110], [90, 100, 80]]))

Your score will be  [[200.57796]]
Other scores will be  [[171.94684]
 [172.55994]]
