# many tools with np and tf

In [8]:
import numpy as  np
import tensorflow as tf

In [6]:
# np.array.ndim
# np.array.shape

In [18]:
t = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])
t.shape

TensorShape([2, 4])

In [51]:
print(tf.reduce_mean([[1., 2.], [3., 4.]], axis=0))
print(np.mean([[1, 2,], [3, 4]], axis=0))

print(tf.reduce_mean([[1., 2.], [3., 4.]], axis=1))
np.mean(np.array([[1, 2,], [3, 4]]), axis=-1)

tf.Tensor([2. 3.], shape=(2,), dtype=float32)
[2. 3.]
tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)


array([1.5, 3.5])

In [56]:
x = [[0., 1., 2.], 
     [2., 1., 0.]]
np.argmax(x, axis=0)

array([1, 0, 0], dtype=int64)

In [59]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]], 
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [67]:
tf.reshape(t, shape=(-1, 3))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])>

In [69]:
tf.reshape(t, shape=(-1, 3)).numpy()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [74]:
tf.reshape(t, shape=(-1, 1, 3)).numpy()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [85]:
np.squeeze([[0], [1], [2]])

array([0, 1, 2])

In [91]:
print(np.expand_dims([0, 1, 2], 0))
print(np.expand_dims([0, 1, 2], 1))

[[0 1 2]]
[[0]
 [1]
 [2]]


In [99]:
tf.one_hot([[0], [1], [2], [0]], depth=3).numpy()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [117]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3).numpy()
tf.reshape(t, shape=[-1, 3]).numpy()
np.reshape(t, [-1, 3])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [131]:
print(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).numpy())
np.cast['int32']([1.8, 2.2, 3.3, 4.9])

[1 2 3 4]


array([1, 2, 3, 4])

In [137]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

print(np.stack([x, y, z], axis=0))
print(np.stack([x, y, z], axis=1))

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [139]:
x = [[0, 1, 2], 
     [2, 1, 0]]
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])