In [1]:
import numpy as np
import tensorflow as tf
import random

# Mnist Data
Tuple of Numpy arrays: (x_train, y_train), (x_test, y_test).
x_train, x_test: uint8 arrays of grayscale image data with shapes (num_samples, 28, 28).

y_train, y_test: uint8 arrays of digit labels (integers in range 0-9) with shapes (num_samples,).

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

In [3]:
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [4]:
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)
print(y_train)
print(y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
# hyper parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 128
dropout_rate = 0.3

In [6]:
model = tf.keras.Sequential()

model.add(tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), input_shape=(28, 28, 1), activation='relu', padding='same'))
model.add(tf.keras.layers.MaxPool2D(pool_size=(2, 2)))
model.add(tf.keras.layers.Dropout(dropout_rate))

model.add(tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu', padding='same'))
model.add(tf.keras.layers.MaxPool2D(pool_size=(2, 2)))
model.add(tf.keras.layers.Dropout(dropout_rate))

model.add(tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu', padding='valid'))
model.add(tf.keras.layers.Dropout(dropout_rate))

model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(units=5 * 5 * 64, kernel_initializer='glorot_normal', activation='relu'))
model.add(tf.keras.layers.Dense(units=10, kernel_initializer='glorot_normal', activation='softmax'))

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 28, 28, 64)        640       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 64)        0         
_________________________________________________________________
dropout (Dropout)            (None, 14, 14, 64)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 14, 14, 64)        36928     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 7, 7, 64)          0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 7, 7, 64)          0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 5, 5, 64)          3

In [8]:
model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(lr=learning_rate), metrics=['binary_accuracy', 'categorical_accuracy'])

In [9]:
history = model.fit(x_train, y_train, batch_size=batch_size, epochs=training_epochs)

Epoch 1/15
469/469 [==============================] - 8s 10ms/step - loss: 4.4727 - binary_accuracy: 0.9386 - categorical_accuracy: 0.6373
Epoch 2/15
469/469 [==============================] - 5s 10ms/step - loss: 0.1758 - binary_accuracy: 0.9891 - categorical_accuracy: 0.9442
Epoch 3/15
469/469 [==============================] - 5s 10ms/step - loss: 0.1149 - binary_accuracy: 0.9928 - categorical_accuracy: 0.9634
Epoch 4/15
469/469 [==============================] - 5s 10ms/step - loss: 0.0861 - binary_accuracy: 0.9947 - categorical_accuracy: 0.9730
Epoch 5/15
469/469 [==============================] - 5s 10ms/step - loss: 0.0738 - binary_accuracy: 0.9954 - categorical_accuracy: 0.9769
Epoch 6/15
469/469 [==============================] - 5s 10ms/step - loss: 0.0642 - binary_accuracy: 0.9961 - categorical_accuracy: 0.9806
Epoch 7/15
469/469 [==============================] - 5s 10ms/step - loss: 0.0633 - binary_accuracy: 0.9960 - categorical_accuracy: 0.9797
Epoch 8/15
469/469 [=======

In [10]:
# predict 10 random hand-writing data
y_predicted = model.predict(x_test)
for x in range(0, 10):
    random_index = random.randint(0, x_test.shape[0]-1)
    print("index: ", random_index,
          "actual y: ", np.argmax(y_test[random_index]),
          "predicted y: ", np.argmax(y_predicted[random_index]))

evaluation = model.evaluate(x_test, y_test)
print('loss: ', evaluation[0])
print('accuracy', evaluation[1])

index:  7110 actual y:  6 predicted y:  6
index:  5176 actual y:  8 predicted y:  8
index:  8802 actual y:  4 predicted y:  4
index:  2390 actual y:  2 predicted y:  2
index:  4484 actual y:  6 predicted y:  6
index:  7467 actual y:  7 predicted y:  7
index:  6417 actual y:  4 predicted y:  4
index:  2218 actual y:  4 predicted y:  4
index:  5142 actual y:  8 predicted y:  8
index:  9590 actual y:  5 predicted y:  5
313/313 [==============================] - 2s 5ms/step - loss: 0.0289 - binary_accuracy: 0.9983 - categorical_accuracy: 0.9907
loss:  0.028875311836600304
accuracy 0.9982596635818481
