In [1]:
import numpy as np
import tensorflow as tf
import random

# Mnist Data
Tuple of Numpy arrays: (x_train, y_train), (x_test, y_test).
x_train, x_test: uint8 arrays of grayscale image data with shapes (num_samples, 28, 28).

y_train, y_test: uint8 arrays of digit labels (integers in range 0-9) with shapes (num_samples,).

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

In [3]:
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [4]:
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)
print(y_train)
print(y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
# hyper parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 128

In [6]:
def make_model(learing_rate):
    model = tf.keras.Sequential()

    model.add(tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), input_shape=(28, 28, 1), activation='relu'))
    model.add(tf.keras.layers.MaxPool2D(pool_size=(2, 2)))

    model.add(tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
    model.add(tf.keras.layers.MaxPool2D(pool_size=(2, 2)))

    model.add(tf.keras.layers.Flatten())
    model.add(tf.keras.layers.Dense(units=10, kernel_initializer='glorot_normal', activation='softmax'))

    model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(lr=learning_rate), metrics=['accuracy'])
    return model

In [7]:
def train_model(x_train, y_train, model):
    history = model.fit(x_train, y_train, batch_size=batch_size, epochs=training_epochs)
    return history

In [8]:
# predict 10 random hand-writing data
def predict_model(x_test, y_test, model):
    y_predicted = model.predict(x_test)
    for x in range(0, 10):
        random_index = random.randint(0, x_test.shape[0]-1)
        print("index: ", random_index,
              "actual y: ", np.argmax(y_test[random_index]),
              "predicted y: ", np.argmax(y_predicted[random_index]))

    evaluation = model.evaluate(x_test, y_test)
    print('loss: ', evaluation[0])
    print('accuracy', evaluation[1])

In [9]:
with tf.device('/cpu:0'):
    model_cpu = make_model(learning_rate)
    history_cpu = train_model(x_train, y_train, model_cpu)
    predict_model(x_test, y_test, model_cpu)

Epoch 1/15
469/469 [==============================] - 31s 64ms/step - loss: 3.1955 - accuracy: 0.8086
Epoch 2/15
469/469 [==============================] - 30s 64ms/step - loss: 0.0976 - accuracy: 0.9722
Epoch 3/15
469/469 [==============================] - 30s 64ms/step - loss: 0.0613 - accuracy: 0.9816
Epoch 4/15
469/469 [==============================] - 30s 63ms/step - loss: 0.0457 - accuracy: 0.9855
Epoch 5/15
469/469 [==============================] - 30s 63ms/step - loss: 0.0372 - accuracy: 0.9883
Epoch 6/15
469/469 [==============================] - 32s 67ms/step - loss: 0.0304 - accuracy: 0.9907
Epoch 7/15
469/469 [==============================] - 32s 68ms/step - loss: 0.0263 - accuracy: 0.9914
Epoch 8/15
469/469 [==============================] - 30s 65ms/step - loss: 0.0237 - accuracy: 0.9921
Epoch 9/15
469/469 [==============================] - 32s 68ms/step - loss: 0.0254 - accuracy: 0.9916
Epoch 10/15
469/469 [==============================] - 32s 69ms/step - loss: 0.022

In [10]:
with tf.device('/gpu:0'):
    model_cpu = make_model(learning_rate)
    history_cpu = train_model(x_train, y_train, model_cpu)
    predict_model(x_test, y_test, model_cpu)

Epoch 1/15
469/469 [==============================] - 6s 7ms/step - loss: 2.9091 - accuracy: 0.8051
Epoch 2/15
469/469 [==============================] - 3s 6ms/step - loss: 0.0931 - accuracy: 0.9734
Epoch 3/15
469/469 [==============================] - 3s 6ms/step - loss: 0.0596 - accuracy: 0.9828
Epoch 4/15
469/469 [==============================] - 3s 6ms/step - loss: 0.0431 - accuracy: 0.9863
Epoch 5/15
469/469 [==============================] - 3s 6ms/step - loss: 0.0343 - accuracy: 0.9880
Epoch 6/15
469/469 [==============================] - 3s 6ms/step - loss: 0.0260 - accuracy: 0.9913
Epoch 7/15
469/469 [==============================] - 3s 6ms/step - loss: 0.0230 - accuracy: 0.9927
Epoch 8/15
469/469 [==============================] - 3s 7ms/step - loss: 0.0206 - accuracy: 0.9928
Epoch 9/15
469/469 [==============================] - 3s 6ms/step - loss: 0.0211 - accuracy: 0.9930
Epoch 10/15
469/469 [==============================] - 3s 6ms/step - loss: 0.0221 - accuracy: 0.9925